# Generated by Django 2.0.4 on 2019-03-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillTree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='parent_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skillTree.Skill'),
        ),
    ]
